[app]
build_directory = "./"
sdk = "C"
#Nanos was deprecated - removed support
#devices = ["nanos", "nanox", "nanos+", "stax", "flex"]
devices = ["nanox", "nanos+", "stax", "flex"]


[tests]
unit_directory = "./unit-tests/"
pytest_directory = "./tests/"