name: check_protobuf_files

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  python_protobuf_check:
    name: Check python protobuf files
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-lite:latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Save current generation
        run: |
          cp -r proto proto_current
          rm proto/*_pb2.py

      - name: Regenerate
        run: |
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python make python_pb
          cp ./vendor/nanopb/generator/proto/nanopb_pb2.py ./proto

      - name: Compare regenerated files with tracked files
        run: |
          diff proto proto_current
